image: cirrusci/flutter:latest

definitions:
  caches:
    flutter: ~/.pub-cache

pipelines:
  default:
    - step:
        name: Build & Test Flutter App
        caches:
          - flutter
        script:
          - git fetch --unshallow || git fetch --all
          - flutter channel stable
          - flutter upgrade
          - flutter doctor -v
          - flutter pub get
          - flutter test
          - flutter build apk --release
